### ISSUE TITLE
AVbin H.264 was not able to decode

### ISSUE THREAD

**Issue by ShellMount** [AVbin/AVbin#58]
As a test, I tried to play the video-1080p-h264.mov downloaded from the link below.
http://avbin.github.io/AVbin/Testing.html
## However, a mistake burned.

D:\DOCUMENT\HuangYuan\VideoPlayer>python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    source = pyglet.media.load('D:\DOCUMENT\HuangYuan\VideoPlayer\VideoSource\video-1080p-h264.mov', streaming=False)
  File "C:\Users\ShellMount\AppData\Local\Programs\Python\Python35\lib\site-packages\pyglet\media\sources\loader.py", line 63, in load
    source = get_source_loader().load(filename, file)
  File "C:\Users\ShellMount\AppData\Local\Programs\Python\Python35\lib\site-packages\pyglet\media\sources\loader.py", line 78, in load
    return AVbinSource(filename, file)
  File "C:\Users\ShellMount\AppData\Local\Programs\Python\Python35\lib\site-packages\pyglet\media\sources\avbin.py", line 242, in **init**
    raise AVbinException('Could not open "%s"' % filename)
pyglet.media.sources.avbin.AVbinException: Could not open "D:\DOCUMENT\HuangYuan\VideoPlayer\VideoSourceideo-1080p-h264.mov"

----------------------THE SOURCE CODE LIKE THIS---------------
player = pyglet.media.Player()
source = pyglet.media.load('D:\DOCUMENT\HuangYuan\VideoPlayer\VideoSource\video-1080p-h264.mov', streaming=False)
player.queue(source)

win = Window(width=640, height=480)

@win.event
def on_draw():
    #print ('加载画面')
    player.get_texture().blit(
                0,
                0,
                width=640,
                height=480)

print ('准备播放')  
player.play()
pyglet.app.run()

---------------------------HOW CAN I DO?------------------

**Comment by RedDevil91** [comment]
You give a wrong path to your file. In your path you should use "/" instead of "\". Try to use this: 
`source = pyglet.media.load('D:/DOCUMENT/HuangYuan/VideoPlayer/VideoSource/video-1080p-h264.mov', streaming=False)`
